server:
  port: 8088

spring:
  application:
    name: book-chat

  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: deepseek-r1:1.5b
          temperature: 0.5 # Меньше креативности = быстрее
          num_predict: 1024 # Короткие ответы
          num_ctx: 4096   # Контекстное окно
      embedding:
        options:
          model: nomic-embed-text:latest

    vectorstore:
      pgvector:
        initialize-schema: true
        dimensions: 768  # Размерность
        index-type: HNSW
        distance-type: COSINE_DISTANCE    # Для индексации: "search_document: "


  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: db/changelog/db.changelog-master.sql
    enabled: true