services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: pgvector_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: books_db
    ports:
      - "5433:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck: # <-- ДОБАВЬТЕ ЭТОТ БЛОК
      test: [ "CMD-SHELL", "pg_isready -U postgres -d books_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: java_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/books_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_PROFILES_ACTIVE: prod
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app-network
    volumes:
      - ./logs:/app/logs

networks:
  app-network:
    driver: bridge